In [59]:
import numpy as np;
import pandas as pd;
import seaborn as sns;
import matplotlib.pyplot as plt;
from sklearn.preprocessing import power_transform
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [39]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [40]:
test.head()

Allied_Nations  Diplomatic_Meetings_Set  Percent_Of_Forces_Mobilized  \
0               8                        0                         0.52   
1               9                        0                         0.44   
2               8                        0                         0.44   
3              10                        0                         0.39   
4               9                        0                         0.44   

   Hostile_Nations  Active_Threats  Inactive_Threats  Citizen_Fear_Index  \
0                2            19.0              52.0            0.376652   
1                2             6.0              12.0            0.254772   
2                3             7.0              18.0            0.472100   
3                2             3.0              13.0            0.478708   
4                2             6.0              14.0            0.561674   

   Closest_Threat_Distance(km)  Aircraft_Carriers_Responding  \
0                       319.06                             1   
1                       351.92                             1   
2                       349.80                             1   
3                       343.44                             1   
4                       346.62                             1   

   Troops_Mobilized(thousands)  ID  
0                     976800.0   1  
1                    1082400.0  10  
2                     924000.0  14  
3                    1003200.0  17  
4                     924000.0  21

In [41]:
train.head()

Allied_Nations  Diplomatic_Meetings_Set  Percent_Of_Forces_Mobilized  \
0              16                        1                         0.67   
1               8                        1                         0.11   
2               9                        1                         0.49   
3               7                        0                         0.30   
4               8                        1                         0.12   

   Hostile_Nations  Active_Threats  Inactive_Threats  Citizen_Fear_Index  \
0                3             6.0              25.0            0.787812   
1                2            38.0              48.0            0.419236   
2                3            32.0              69.0            0.582232   
3                2            31.0              52.0            0.589574   
4                5            13.0              42.0            0.552863   

   Closest_Threat_Distance(km)  Aircraft_Carriers_Responding  \
0                       324.36                             1   
1                       359.34                             0   
2                       332.84                             1   
3                       358.28                             1   
4                       364.64                             0   

   Troops_Mobilized(thousands)  DEFCON_Level     ID  
0                     862400.0             3   7570  
1                     959200.0             4  12128  
2                     836000.0             3   2181  
3                     924000.0             3   5946  
4                     968000.0             2   9054

In [42]:
train.isnull().sum()

Allied_Nations                  0
Diplomatic_Meetings_Set         0
Percent_Of_Forces_Mobilized     0
Hostile_Nations                 0
Active_Threats                  0
Inactive_Threats                0
Citizen_Fear_Index              0
Closest_Threat_Distance(km)     0
Aircraft_Carriers_Responding    0
Troops_Mobilized(thousands)     0
DEFCON_Level                    0
ID                              0
dtype: int64

In [43]:
train.skew()

Allied_Nations                  0.915132
Diplomatic_Meetings_Set        -0.086937
Percent_Of_Forces_Mobilized     0.310250
Hostile_Nations                 4.352497
Active_Threats                  1.232349
Inactive_Threats                1.669572
Citizen_Fear_Index              0.058511
Closest_Threat_Distance(km)     0.231703
Aircraft_Carriers_Responding   -2.023844
Troops_Mobilized(thousands)     0.807094
DEFCON_Level                    0.350631
ID                             -0.006091
dtype: float64

In [44]:
predictors = train.iloc[:,0:10]
target = train.iloc[:,10]
test_n = test.iloc[:,0:10]
test_pred = test_n.columns

In [45]:
target

0       3
1       4
2       3
3       3
4       2
       ..
9995    4
9996    3
9997    3
9998    2
9999    2
Name: DEFCON_Level, Length: 10000, dtype: int64

In [46]:
train.head()

Allied_Nations  Diplomatic_Meetings_Set  Percent_Of_Forces_Mobilized  \
0              16                        1                         0.67   
1               8                        1                         0.11   
2               9                        1                         0.49   
3               7                        0                         0.30   
4               8                        1                         0.12   

   Hostile_Nations  Active_Threats  Inactive_Threats  Citizen_Fear_Index  \
0                3             6.0              25.0            0.787812   
1                2            38.0              48.0            0.419236   
2                3            32.0              69.0            0.582232   
3                2            31.0              52.0            0.589574   
4                5            13.0              42.0            0.552863   

   Closest_Threat_Distance(km)  Aircraft_Carriers_Responding  \
0                       324.36                             1   
1                       359.34                             0   
2                       332.84                             1   
3                       358.28                             1   
4                       364.64                             0   

   Troops_Mobilized(thousands)  DEFCON_Level     ID  
0                     862400.0             3   7570  
1                     959200.0             4  12128  
2                     836000.0             3   2181  
3                     924000.0             3   5946  
4                     968000.0             2   9054

In [47]:
predictors.head()

Allied_Nations  Diplomatic_Meetings_Set  Percent_Of_Forces_Mobilized  \
0              16                        1                         0.67   
1               8                        1                         0.11   
2               9                        1                         0.49   
3               7                        0                         0.30   
4               8                        1                         0.12   

   Hostile_Nations  Active_Threats  Inactive_Threats  Citizen_Fear_Index  \
0                3             6.0              25.0            0.787812   
1                2            38.0              48.0            0.419236   
2                3            32.0              69.0            0.582232   
3                2            31.0              52.0            0.589574   
4                5            13.0              42.0            0.552863   

   Closest_Threat_Distance(km)  Aircraft_Carriers_Responding  \
0                       324.36                             1   
1                       359.34                             0   
2                       332.84                             1   
3                       358.28                             1   
4                       364.64                             0   

   Troops_Mobilized(thousands)  
0                     862400.0  
1                     959200.0  
2                     836000.0  
3                     924000.0  
4                     968000.0

In [48]:
predictors.columns

Index(['Allied_Nations', 'Diplomatic_Meetings_Set',
       'Percent_Of_Forces_Mobilized', 'Hostile_Nations', 'Active_Threats',
       'Inactive_Threats', 'Citizen_Fear_Index', 'Closest_Threat_Distance(km)',
       'Aircraft_Carriers_Responding', 'Troops_Mobilized(thousands)'],
      dtype='object')

In [49]:
scaler = MinMaxScaler()
scaler.fit(predictors)
scaler.fit(test_n)
train_n = scaler.transform(predictors)
test_n = scaler.transform(test_n)

In [50]:
train_n[0]

array([1.        , 0.5       , 0.67      , 0.13333333, 0.07042254,
       0.06713781, 0.78781204, 0.2519685 , 0.5       , 0.25      ])

In [51]:
train_n = np.array(train_n)
test_n = np.array(test_n)

In [52]:
pred_norm = pd.DataFrame(data=train_n, columns = predictors.columns)
test_norm = pd.DataFrame(data = test_n, columns = test_pred)

In [54]:
pred_norm.head()

Allied_Nations  Diplomatic_Meetings_Set  Percent_Of_Forces_Mobilized  \
0        1.000000                      0.5                         0.67   
1        0.272727                      0.5                         0.11   
2        0.363636                      0.5                         0.49   
3        0.181818                      0.0                         0.30   
4        0.272727                      0.5                         0.12   

   Hostile_Nations  Active_Threats  Inactive_Threats  Citizen_Fear_Index  \
0         0.133333        0.070423          0.067138            0.787812   
1         0.066667        0.521127          0.148410            0.419236   
2         0.133333        0.436620          0.222615            0.582232   
3         0.066667        0.422535          0.162544            0.589574   
4         0.266667        0.169014          0.127208            0.552863   

   Closest_Threat_Distance(km)  Aircraft_Carriers_Responding  \
0                     0.251969                           0.5   
1                     0.511811                           0.0   
2                     0.314961                           0.5   
3                     0.503937                           0.5   
4                     0.551181                           0.0   

   Troops_Mobilized(thousands)  
0                     0.250000  
1                     0.446429  
2                     0.196429  
3                     0.375000  
4                     0.464286

In [55]:
test_norm.head()

Allied_Nations  Diplomatic_Meetings_Set  Percent_Of_Forces_Mobilized  \
0        0.272727                      0.0                         0.52   
1        0.363636                      0.0                         0.44   
2        0.272727                      0.0                         0.44   
3        0.454545                      0.0                         0.39   
4        0.363636                      0.0                         0.44   

   Hostile_Nations  Active_Threats  Inactive_Threats  Citizen_Fear_Index  \
0         0.066667        0.253521          0.162544            0.376652   
1         0.066667        0.070423          0.021201            0.254772   
2         0.133333        0.084507          0.042403            0.472100   
3         0.066667        0.028169          0.024735            0.478708   
4         0.066667        0.070423          0.028269            0.561674   

   Closest_Threat_Distance(km)  Aircraft_Carriers_Responding  \
0                     0.212598                           0.5   
1                     0.456693                           0.5   
2                     0.440945                           0.5   
3                     0.393701                           0.5   
4                     0.417323                           0.5   

   Troops_Mobilized(thousands)  
0                     0.482143  
1                     0.696429  
2                     0.375000  
3                     0.535714  
4                     0.375000

In [21]:
log = LogisticRegression()
log.fit(pred_norm, target)

C:\Users\suraj\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\suraj\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
predictions = log.predict(test_norm)

In [23]:
predictions

array([3, 3, 3, ..., 2, 3, 2], dtype=int64)

In [24]:
dicti = {}
dicti['ID'] = test.ID
dicti['DEFCON_Level'] = np.array(predictions)

In [32]:
dicti

{'ID': 0           1
 1          10
 2          14
 3          17
 4          21
         ...  
 2495    12484
 2496    12487
 2497    12488
 2498    12491
 2499    12493
 Name: ID, Length: 2500, dtype: int64,
 'DEFCON_Level': array([3, 3, 3, ..., 2, 3, 2], dtype=int64)}

In [46]:
output = pd.DataFrame(dicti)

In [47]:
output.to_csv('output.csv', index=False)

In [94]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=1000)
rfc.fit(pred_norm, target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [95]:
rfc_train_pred = rfc.predict(pred_norm)

In [96]:
print(confusion_matrix(target,rfc_train_pred))

[[ 498    0    0    0    0]
 [   0 4269    1    0    0]
 [   0    1 3909    0    0]
 [   0    0    0 1212    0]
 [   0    0    0    0  110]]


In [91]:
rfc_test_pred = rfc.predict(test_norm)

In [92]:
rfc_test_pred

array([4, 3, 3, ..., 2, 4, 2], dtype=int64)

In [93]:
dicti = {}
dicti['ID'] = test.ID
dicti['DEFCON_Level'] = np.array(rfc_test_pred)
output = pd.DataFrame(dicti)
output.to_csv('output_rf_2.csv', index=False)

In [66]:
# !pip install xgboost
from xgboost import XGBClassifier

In [73]:
model = XGBClassifier()
model = XGBClassifier(silent=False, 
                      scale_pos_weight=1,
                      learning_rate=0.01,  
                      colsample_bytree = 0.4,
                      subsample = 0.8,
                      n_estimators=1000, 
                      reg_alpha = 0.3,
                      max_depth=4, 
                      gamma=10)
model.fit(pred_norm, target)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, gamma=10, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.01, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0.3,
              reg_lambda=1, scale_pos_weight=1, silent=False, subsample=0.8,
              tree_method=None, validate_parameters=False, verbosity=None)

In [74]:
xgb_train_pred = model.predict(pred_norm)

In [75]:
print(confusion_matrix(target,xgb_train_pred))

[[   9  285  200    4    0]
 [   2 3145 1112   11    0]
 [   1 1388 2399  122    0]
 [   0   83  855  274    0]
 [   0    7   72   31    0]]


In [76]:
xgb_test_pred = model.predict(test_norm)

In [77]:
xgb_test_pred

array([3, 4, 3, ..., 2, 3, 2], dtype=int64)

In [79]:
from sklearn.neighbors import KNeighborsClassifier
knn  = KNeighborsClassifier(n_neighbors=5)
knn.fit(pred_norm, target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [80]:
knn_train_pred = knn.predict(pred_norm)

In [81]:
print(confusion_matrix(target,knn_train_pred))

[[ 178  247   64    9    0]
 [ 106 3505  625   33    1]
 [  56 1002 2672  178    2]
 [  10  178  477  547    0]
 [   2   17   36   50    5]]


In [ ]:
dicti = {}
dicti['ID'] = test.ID
dicti['DEFCON_Level'] = np.array(xgb_test_pred)
output = pd.DataFrame(dicti)
output.to_csv('output_xgb_1.csv', index=False)